# -*- coding: utf-8 -*-
"""EDA_LAB1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1V5gmjkj8BRYfAaDknImMlqeVircqieAk
"""

import numpy as np
import matplotlib.pyplot as plt

# Todas las dimensiones de Conjuntos de datos
dimensions = [10, 50, 100, 500, 1000, 2000, 5000]

for dim in dimensions:
    # Cargar los datos desde el archivo txt
    distances = np.loadtxt("distances_" + str(dim) + ".txt")

    # Generación del histograma
    plt.hist(distances, bins=20)
    plt.xlabel("Distancia")
    plt.ylabel("Frecuencia")
    plt.title("Histograma de Distancias (Dimensión " + str(dim) + ")")
    plt.show()